_target_: pytorch_lightning.callbacks.ModelCheckpoint
save_top_k: 3
save_last: True
verbose: True
#monitor: eval_lh/avg_seq_len
monitor: val_act/lang_act_loss_pp
mode: min
dirpath: saved_models
filename: '{epoch:02d}_{val_act/lang_act_loss_pp:.2f}' #put back in when PL fixes this _{val/accuracy:.4f}'
every_n_epochs: 1
